### ISSUE TITLE
json to cursor issue

### ISSUE THREAD

**Issue by ChrisBerkvens** [Irwin1985/JSONFox#18]
Hi Irwin,
I was trying your jsonfox app, but couldn't get the data into a cursor. 
See files in attachment. 
Eventually, i want to convert a Json file to a DBF file. (to several DBF files if needed) 
Best regards, chris 

[block677425.zip](https://github.com/Irwin1985/JSONFox/files/6252348/block677425.zip)
[block677450.zip](https://github.com/Irwin1985/JSONFox/files/6252352/block677450.zip)

see also;
https://blockchain.info/block-height/677425?format=json 
https://blockchain.info/block-height/677450?format=json

**Comment by Irwin1985** [comment]
Hi Chris, your data has a mixture of nested objects and arrays thus is kinda complex to extract the rows you need to convert into a cursor. In order to successfully convert to cursor JSONFox needs to read the following format from the input: '[' '{' keyValuePair '}' ']'

Where keyValuePair does not allow nested arrays nor objects for the benefit of cursor structure: COLUMNS (ROWS)+

**Comment by ChrisBerkvens** [comment]
Thank you Irwin. Even commercial jsonto... apps can't do this.
